name: Build-apk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git zip unzip openjdk-11-jdk libncurses6 libstdc++6 libffi-dev libssl-dev
          pip install --upgrade cython buildozer

      - name: Install SDK/NDK etc
        run: |
          # Set Android SDK root
          export ANDROID_SDK_ROOT=$HOME/Android/Sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

          # Accept licenses
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

          # Install SDK components
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.0"

      - name: Setting up and building
        run: |
          cd app/
          buildozer init
          buildozer android debug
